document.writeln('<div class="footer">')
document.writeln('<div class="wrap">')
document.writeln('<div class="title"></div>')
document.writeln('<div class="desc">“聚运动”JUJU SPORTS是一家专注于中国足球人才培养和输送的“互联网+体育”公司。中国足球事业空前繁荣，足球人才却遇到瓶颈，聚运动应时而生，从欧足联引进全球顶级教练团队，成立可可维奇足球学院，从青少年兴趣足球、业余校队培训开始，深耕足球人才土壤。同时，聚运动着力搭建青训队伍足球竞技互联网平台，引入世界各地顶级俱乐部青训球队，展开全球邀请赛，锤炼人才，输送给中国足球事业。聚运动关注人才全面发展，通过“学籍计划”、“大学计划”、“常青藤计划”，让好苗子们踢球的同时可以获得最好的教育，打通就业路径，免去职业生涯的后顾之忧。<br><br>聚运动自成立以来扎实耕耘，已成功启动外籍教练“送教上门”、“校园足球教练员培训“、“校园体坛风云人物”等国内标杆项目，步步为营，正在把远大梦想积累成现实。<br><br>“聚运动”愿成中国足球的“人才梦工厂”。</div>')
document.writeln('<div class="link_box">')
document.writeln('<a href="counseling.html">资讯</a>')
document.writeln('<a href="college_lesson.html">学院</a>')
document.writeln('<a href="battle.html">约战</a>')
document.writeln('<a href="myaccount.html">我的运动</a>')
document.writeln('<a class="noma" href="joinus.html">公司介绍</a>')
document.writeln('</div>')
document.writeln('<div class="tel">电话：86-21-66302828<br>传真：86-21-33831679</div>')
document.writeln('<div class="adr">地址：上海市徐汇区淮海中路1010号嘉华中心2903室</div>')
document.writeln('<div class="copyright">CopyRight©2015 上海聚运动文化传播有限公司 <br> All Rigths Reserved 沪ICP备15015551号-1</div>')
document.writeln('<div class="wxcode"></div>')
document.writeln('</div>')
document.writeln('</div>')